import Foundation

enum Breed: String, CaseIterable, Identifiable {
    case mixed                        = "MIXED"
    case akita                        = "AKITA"
    case airedaleTerrier              = "AIREDALE_TERRIER"
    case alaskanMalamute              = "ALASKAN_MALAMUTE"
    case americanBulldog              = "AMERICAN_BULLDOG"
    case americanCockerSpaniel        = "AMERICAN_COCKER_SPANIEL"
    case americanPitBullTerrier       = "AMERICAN_PIT_BULL_TERRIER"
    case americanStaffordshireTerrier = "AMERICAN_STAFFORDSHIRE_TERRIER"
    case australianCattleDog          = "AUSTRALIAN_CATTLE_DOG"
    case australianShepherd           = "AUSTRALIAN_SHEPHERD"
    case australianTerrier            = "AUSTRALIAN_TERRIER"
    case basenji                      = "BASENJI"
    case bassadorHound                = "BASSADOR_HOUND"
    case beagle                       = "BEAGLE"
    case beardedCollie                = "BEARDED_COLLIE"
    case beauceron                    = "BEAUCERON"
    case bedlingtonTerrier            = "BEDLINGTON_TERRIER"
    case belgianMalinois              = "BELGIAN_MALINOIS"
    case belgianSheepdog              = "BELGIAN_SHEEPDOG"
    case berneseMountainDog           = "BERNESE_MOUNTAIN_DOG"
    case bichonFrise                  = "BICHON_FRISE"
    case blackAndTanCoonhound         = "BLACK_AND_TAN_COONHOUND"
    case blackRussianTerrier          = "BLACK_RUSSIAN_TERRIER"
    case bloodhound                   = "BLOODHOUND"
    case borderCollie                 = "BORDER_COLLIE"
    case borderTerrier                = "BORDER_TERRIER"
    case borzoi                       = "BORZOI"
    case bostonTerrier                = "BOSTON_TERRIER"
    case boxer                        = "BOXER"
    case boykinSpaniel                = "BOYKIN_SPANIEL"
    case briard                       = "BRIARD"
    case brittany                     = "BRITTANY"
    case bullTerrier                  = "BULL_TERRIER"
    case bulldog                      = "BULLDOG"
    case bullmastiff                  = "BULLMASTIFF"
    case cairnTerrier                 = "CAIRN_TERRIER"
    case cavalierKingCharlesSpaniel   = "CAVALIER_KING_CHARLES_SPANIEL"
    case chihuahua                    = "CHIHUAHUA"
    case chineseCrested               = "CHINESE_CRESTED"
    case chowChow                     = "CHOW_CHOW"
    case clumberSpaniel               = "CLUMBER_SPANIEL"
    case cockapoo                     = "COCKAPOO"
    case cockerSpaniel                = "COCKER_SPANIEL"
    case collie                       = "COLLIE"
    case corgi                        = "CORGI"
    case cotonDeTulear                = "COTON_DE_TULEAR"
    case curlyCoatedRetriever         = "CURLY_COATED_RETRIEVER"
    case dachshund                    = "DACHSHUND"
    case dalmatian                    = "DALMATIAN"
    case dandieDinmontTerrier         = "DANDIE_DINMONT_TERRIER"
    case dobermanPinscher             = "DOBERMAN_PINSCHER"
    case englishBulldog               = "ENGLISH_BULLDOG"
    case englishCockerSpaniel         = "ENGLISH_COCKER_SPANIEL"
    case englishSetter                = "ENGLISH_SETTER"
    case englishSpringerSpaniel       = "ENGLISH_SPRINGER_SPANIEL"
    case fieldSpaniel                 = "FIELD_SPANIEL"
    case finnishLapphund              = "FINNISH_LAPPHUND"
    case finnishSpitz                 = "FINNISH_SPITZ"
    case frenchBulldog                = "FRENCH_BULLDOG"
    case germanPinscher               = "GERMAN_PINSCHER"
    case germanShepherd               = "GERMAN_SHEPHERD"
    case germanShorthairedPointer     = "GERMAN_SHORTHAIRED_POINTER"
    case giantSchnauzer               = "GIANT_SCHNAUZER"
    case glenOfImaalTerrier           = "GLEN_OF_IMAAL_TERRIER"
    case goldador                     = "GOLDADOR"
    case goldenRetriever              = "GOLDEN_RETRIEVER"
    case goldendoodle                 = "GOLDENDOODLE"
    case greatDane                    = "GREAT_DANE"
    case greatPyrenees                = "GREAT_PYRENEES"
    case greaterSwissMountainDog      = "GREATER_SWISS_MOUNTAIN_DOG"
    case greyhound                    = "GREYHOUND"
    case havanese                     = "HAVANESE"
    case irishSetter                  = "IRISH_SETTER"
    case irishTerrier                 = "IRISH_TERRIER"
    case irishWaterSpaniel            = "IRISH_WATER_SPANIEL"
    case italianGreyhound             = "ITALIAN_GREYHOUND"
    case jackRussellTerrier           = "JACK_RUSSELL_TERRIER"
    case japaneseChin                 = "JAPANESE_CHIN"
    case keeshond                     = "KEESHOND"
    case kingCharlesSpaniel           = "KING_CHARLES_SPANIEL"
    case labradorRetriever            = "LABRADOR_RETRIEVER"
    case lakelandTerrier              = "LAKELAND_TERRIER"
    case lhasaApso                    = "LHASA_APSO"
    case maltese                      = "MALTESE"
    case manchesterTerrier            = "MANCHESTER_TERRIER"
    case mastiff                      = "MASTIFF"
    case miniatureBullTerrier         = "MINIATURE_BULL_TERRIER"
    case miniaturePinscher            = "MINIATURE_PINSCHER"
    case newfoundland                 = "NEWFOUNDLAND"
    case norfolkTerrier               = "NORFOLK_TERRIER"
    case norwegianElkhound            = "NORWEGIAN_ELKHOUND"
    case norwichTerrier               = "NORWICH_TERRIER"
    case oldEnglishSheepdog           = "OLD_ENGLISH_SHEEPDOG"
    case papillon                     = "PAPILLON"
    case parsonRussellTerrier         = "PARSON_RUSSELL_TERRIER"
    case pekingese                    = "PEKINGESE"
    case pembrokeWelshCorgi           = "PEMBROKE_WELSH_CORGI"
    case pitBullTerrier               = "PIT_BULL_TERRIER"
    case plottHound                   = "PLOTT_HOUND"
    case pointer                      = "POINTER"
    case polishLowlandSheepdog        = "POLISH_LOWLAND_SHEEPDOG"
    case pomeranian                   = "POMERANIAN"
    case poodle                       = "POODLE"
    case portugueseWaterDog           = "PORTUGUESE_WATER_DOG"
    case pug                          = "PUG"
    case rhodesianRidgeback           = "RHODESIAN_RIDGEBACK"
    case rottweiler                   = "ROTTWEILER"
    case saintBernard                 = "SAINT_BERNARD"
    case saluki                       = "SALUKI"
    case samoyed                      = "SAMOYED"
    case schipperke                   = "SCHIPPERKE"
    case schnauzer                    = "SCHNAUZER"
    case scottishTerrier              = "SCOTTISH_TERRIER"
    case sealyhamTerrier              = "SEALYHAM_TERRIER"
    case shetlandSheepdog             = "SHETLAND_SHEEPDOG"
    case shibaInu                     = "SHIBA_INU"
    case shihTzu                      = "SHIH_TZU"
    case siberianHusky                = "SIBERIAN_HUSKY"
    case silkyTerrier                 = "SILKY_TERRIER"
    case staffordshireBullTerrier     = "STAFFORDSHIRE_BULL_TERRIER"
    case sussexSpaniel                = "SUSSEX_SPANIEL"
    case tibetanMastiff               = "TIBETAN_MASTIFF"
    case tibetanSpaniel               = "TIBETAN_SPANIEL"
    case toyFoxTerrier                = "TOY_FOX_TERRIER"
    case vizsla                       = "VIZSLA"
    case weimaraner                   = "WEIMARANER"
    case welshSpringerSpaniel         = "WELSH_SPRINGER_SPANIEL"
    case westHighlandWhiteTerrier     = "WEST_HIGHLAND_WHITE_TERRIER"
    case whippet                      = "WHIPPET"
    case wireFoxTerrier               = "WIRE_FOX_TERRIER"
    case xoloitzcuintli               = "XOLOITZCUINTLI"
    case yorkshireTerrier             = "YORKSHIRE_TERRIER"

    // Identifiable conformance
    var id: String { rawValue }

    /// Turns "AMERICAN_BULLDOG" → "American Bulldog"
    var displayName: String {
        rawValue
            .lowercased()
            .split(separator: "_")
            .map { $0.capitalized }
            .joined(separator: " ")
    }
}
